# Generated by Django 4.0.4 on 2022-06-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplatform', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover_photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
